name: Build Application
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]


jobs:
  build:
    name: run build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test build
        run: |
          make

      - name: Test format
        run: |
          test -z $(gofmt  -l .)
